import Head from 'next/head'
import Image from 'next/image'
import { Mulish } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const mulish = Mulish({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          <Image src="/images/intro.jpg" alt="Chat" width={262} height={271}/>
          <h1>Connect easily with your family and friends over countries</h1>
          <small>Terms & Privacy Policy</small>
          <Link href="/">Start Messaging</Link>
        </section>
      </main>
    </>
  )
}
